paritytech/substrate-light-ui

packages/electron-app/package.json
packages/electron-app/src/main/index.ts
yarn.lock

easier debugging with electron

React Developer Tools

---

packages/identity-app/src/Create.tsx
packages/light-apps/src/IdentityCard/IdentityCard.tsx
packages/light-apps/src/Onboarding/CreateNewAccountScreen.tsx
packages/transfer-app/src/SendBalance.tsx
packages/ui-api/src/ApiGate.tsx
packages/ui-components/src/TextArea.tsx
packages/ui-components/src/index.ts

rewrite recovery phrase

---

packages/light-apps/src/IdentityCard/IdentityCard.tsx

clean up forget and backup modal ui

---

package.json
packages/light-apps/tsconfig.json

fix #100 get build passing again

nohoist the problem dev dependencies

---

packages/transfer-app/src/Saved.tsx
packages/transfer-app/src/SendBalance.tsx

fix(transfer-app): Make the recipient clickable

---

packages/light-apps/src/IdentityCard/IdentityCard.tsx
packages/transfer-app/src/SentBalance.tsx
packages/ui-api/package.json
yarn.lock

bump @polkadot/api to 0.75.1

---

packages/electron-app/src/main/index.ts
packages/electron-app/src/main/util/staticPath.ts

fix: Ignore ELECTRON_START_URL in production

---

packages/ui-api/package.json
packages/ui-components/package.json
yarn.lock

chore(deps): Bump api, ui-api, ui-signer

---

packages/light-apps/src/IdentityHeader/IdentityHeader.tsx
packages/light-apps/src/SavedAddresses.tsx
packages/ui-components/src/CopyButton.tsx
packages/ui-components/src/index.ts

added some clean up of header as well.
https://github.com/paritytech/substrate-light-ui/issues/276

Add ability to copy address in header and address book

---

packages/electron-app/package.json
packages/electron-app/src/main/app/menu.ts
packages/electron-app/src/main/index.ts
yarn.lock

fixes #307 
Also removed ELECTRON_START_URL, it's a bit useless

chore(electron-app): Update to Electron 5

---

yarn.lock

Revert #368, CI didn't pass on that one.

fix: Revert #368 and fix lint bug

---

packages/electron-app/package.json
packages/electron-app/src/main/app/isSubstrateRunning.ts
yarn.lock

chore: Update axios

---

packages/governance-app/src/Democracy/ProposalRow.tsx
packages/governance-app/src/Democracy/ReferendumRow.tsx
packages/light-apps/src/Content/Content.tsx
packages/transfer-app/src/SendBalance/types.ts
packages/transfer-app/src/SendBalance/validate.ts
packages/ui-common/src/TxQueueContext.tsx
packages/ui-common/src/types.ts
packages/ui-common/src/util/validate.ts
packages/ui-components/src/TxDetails.tsx
packages/ui-components/src/TxSummary.tsx

feat: Seconding and Voting

---

packages/accounts-app/src/Staking/Bond.tsx
packages/accounts-app/src/Validators/FinalConfirmation.tsx
packages/light-apps/src/App.tsx
packages/light-apps/src/Content/Content.tsx
packages/light-apps/src/Signer/Signer.tsx
packages/light-apps/src/TxQueueNotifier/TxQueueNotifier.tsx
packages/transfer-app/src/SendBalance/SendBalance.tsx
packages/transfer-app/src/Transfer.tsx
packages/ui-common/src/AlertsContext.tsx
packages/ui-common/src/TxQueueContext.tsx
packages/ui-components/src/Alert.tsx

Feat: TxQueue Cancel Observable + Alert timeout

---

packages/light-apps/src/IdentityHeader/IdentityHeader.tsx

closes #350
left out transfer since it is getting whacked

fix #350: show active tab

---

packages/accounts-app/src/Validators/ValidatorsList.tsx
packages/ui-components/src/Alert.tsx
packages/ui-components/src/BalanceDisplay.tsx
packages/ui-components/src/stateful/InputAddress.tsx

Small PR to fix some `div` in `p` erros, as well as React prop types errors.

fix: Make all console.error disappear

---

.gitignore
package.json
packages/accounts-app/package.json
packages/light-apps/src/IdentityHeader/IdentityHeader.tsx
packages/transfer-app/package.json
yarn.lock

also spacing and alignment and colors and other little stuff

fix: identity header

---

packages/accounts-app/src/AddAccount/Create/CreateAccount.tsx
packages/accounts-app/src/AddAccount/Create/subComponents.tsx
packages/accounts-app/src/AddAccount/ImportWithJson.tsx
packages/accounts-app/src/AddAccount/ImportWithPhrase.tsx
packages/accounts-app/src/ManageAddresses/SaveAddress/SaveAddress.tsx
packages/accounts-app/src/Overview/BalanceOverview.tsx
packages/accounts-app/src/types.ts
packages/electron-app/src/main/app/substrateProcess.ts
packages/extension-app/src/background/index.ts
packages/extension-app/src/types.ts
packages/extension-app/tsconfig.json
packages/light-apps/src/IdentityHeader/IdentityHeader.tsx
packages/light-apps/src/TxQueueNotifier/TxQueueNotifier.tsx
scripts/prestart.sh

- remove all `any` (1 left, don't know what to do about it)
- fix all eslint warnings
- close #454

refactor: Small code grooming

---

packages/light-apps/package.json
packages/light-apps/src/IdentityHeader/IdentityHeader.tsx
packages/light-apps/src/IdentityHeader/InputAddress/InputAddress.tsx
packages/light-apps/src/IdentityHeader/InputAddress/index.ts
packages/light-apps/src/TopBar/TopBar.tsx
yarn.lock

blocked by https://github.com/paritytech/Nomidot/pull/145

fix(light-apps): Make IdentityHeader nicer

---

CONTRIBUTING.md
README.md
tslint.json
yarn.lock

I just released v0.3.0 (the extension poc milestone), let's start the next milestone now

chore: Update README and guidelines

---

lerna.json
package.json
packages/electron-app/README.md
packages/electron-app/package.json
packages/extension-app/package.json
packages/extension-app/src/manifest.json

0.3.0 has been released, let's start a new chapter with 0.4.0

chore: Bump everywhere to version 0.4.0

---

lerna.json
package.json
packages/electron-app/package.json
packages/extension-app/package.json
packages/extension-app/static/manifest.json
packages/light-apps/package.json
packages/light-apps/src/Accounts/AddAccount/Create/CreateAccount.tsx
packages/light-apps/src/Accounts/AddAccount/ImportWithJson.tsx
packages/light-apps/src/Accounts/AddAccount/util.ts
packages/light-apps/src/Accounts/OverviewCard.tsx
packages/light-apps/src/Transfer/SendBalance/SendBalance.tsx
packages/light/package.json
packages/ui-components/package.json
packages/ui-components/src/stateful/Balance.tsx
yarn.lock

- Update to @polkadot/api@1.4.1
- Fix lint issues due to latest typescript

chore(deps): Update to @polkadot/api@1.4.1

---

packages/ui-components/package.json
packages/ui-components/src/InputAddress.tsx
packages/ui-components/src/util/checkInstanceOf.ts
packages/ui-components/stories/InputAddress.stories.tsx
yarn.lock

feat: make InputAddress work with extension Injected accounts

---

packages/ui-components/package.json
packages/ui-components/src/InputAddress.tsx
packages/ui-components/stories/InputAddress.stories.tsx

fix: compare public keys

---

package.json
packages/electron-app/tsconfig.json
packages/extension-app/tsconfig.json
packages/light-apps/package.json
packages/light-apps/tsconfig.json
packages/light/tsconfig.json
tsconfig.json
yarn.lock

chore(deps): Update @polkadot/api to 1.7.1

---

package.json
packages/electron-app/scripts/fetchLatestSubstrate.js
packages/electron-app/src/main/app/substrateProcess.ts
packages/electron-app/src/main/index.ts
packages/electron-app/src/main/util/logger.ts
packages/light-apps/src/Accounts/AddAccount/Create/CreateAccount.tsx
packages/light-apps/src/Accounts/AddAccount/Create/subComponents.tsx
packages/light-apps/src/Accounts/AddAccount/ImportWithPhrase.tsx
packages/light-apps/src/Accounts/AddAccount/util.ts
packages/light-apps/src/Accounts/Overview.tsx
packages/light-apps/src/ContextGate/context/KeyringContext/KeyringContext.tsx
packages/light-apps/src/ContextGate/context/ProviderContext/ProviderContext.tsx
packages/light-apps/src/Signer/Signer.tsx
packages/light-apps/src/TopBar/ChooseProvider/ChooseProvider.tsx
packages/light-apps/src/Transfer/SendBalance/SendBalance.tsx
packages/light-apps/src/Transfer/SendBalance/Validation.tsx
packages/light-apps/src/Transfer/SendBalance/validate.ts
packages/light-apps/src/TxQueueNotifier/TxQueueNotifier.tsx
packages/ui-components/src/Alert.tsx
packages/ui-components/src/Circle.tsx
packages/ui-components/src/InputFile.tsx
yarn.lock

chore: Use prettier v2 everywhere

---

packages/ui-components/src/Loading.tsx

fix: add back inline prop for loadding component

---

packages/light-apps/src/pages/Accounts/Add/Restore/WithPhrase.tsx

fix: TextArea unfocuses onChange

---

packages/light-apps/package.json
packages/light-apps/src/components/ContextGate/ContextGate.tsx
packages/light-apps/src/components/TopBar/ChooseProvider/ChooseProvider.tsx
packages/light-apps/src/components/TopBar/TopBar.tsx
packages/light-apps/src/components/context/AccountContext/AccountContext.tsx
packages/light-apps/src/components/context/InjectedContext/InjectedContext.tsx
packages/light-apps/src/components/context/ProviderContext/ProviderContext.tsx
packages/light-apps/src/react-app-env.d.ts
packages/light/src/kusama_cc3/fromUrl.ts
packages/light/src/westend/fromUrl.ts
packages/ui-components/package.json
tsconfig.json
yarn.lock

Mostly cleaning up some code:
- Highligh "Accounts" tab in TopBar even when loading
- Unsubscribe in some useEffects
- Don't web3Enable polkadot-js extension, even when it's detected. We can think of polkadot-js extension integration later
- split chainSpec.jsons into separate chunks, loading dynamically
- update some packages

fix: Polish In-Tab wasm browser experience

---

.github/workflows/pr.yml
README.md
package.json

ci: Deploy artifacts as draft release

---

packages/light-apps/package.json
packages/light-apps/src/components/ContextGate/ContextGate.tsx
packages/light-apps/src/components/TopBar/ChooseProvider/ChooseProvider.tsx
packages/light-apps/src/components/context/AccountContext/AccountContext.tsx
packages/light-apps/src/components/context/InjectedContext/InjectedContext.tsx
packages/light-apps/src/pages/Accounts/Overview/Overview.tsx
packages/light-apps/src/pages/Accounts/Overview/PjsButton/PjsButton.tsx
packages/light-apps/src/pages/Accounts/Overview/PjsButton/index.ts
packages/light-apps/src/react-app-env.d.ts

fix(light-apps): Add button to connect to PolkadotJS

---

packages/ui-components/src/Circle.tsx
packages/ui-components/src/Menu.tsx

This fixes all the warnings in the console.

fix(ui-components): Remove warnings from styled-components

---

.github/workflows/pr.yml

ci: Create a draft release with the extension

---

packages/extension-app/package.json
packages/extension-app/src/background/clients.ts
packages/extension-app/src/background/index.ts
packages/light-apps/package.json
packages/light-apps/src/components/TopBar/ChooseProvider/discover.ts
packages/light-apps/src/components/context/ProviderContext/ProviderContext.tsx
packages/light-apps/src/util/env.ts
packages/light/src/kusama_cc3/fromUrl.ts
packages/light/src/westend/fromUrl.ts
packages/ui-components/src/Paragraph.tsx
packages/ui-components/src/TextArea.tsx
yarn.lock

If you're running a local node, lichen connects to it.

feat(light-apps): Discover local node too
